#pragma once

#include <glib-object.h>

/* *INDENT-OFF* */
G_BEGIN_DECLS

typedef enum
{
  WYREBOX_ADMIN_HEALTH_STATUS_HEALTHY,
  WYREBOX_ADMIN_HEALTH_STATUS_DEGRADED,
  WYREBOX_ADMIN_HEALTH_STATUS_REPLAYING,
  WYREBOX_ADMIN_HEALTH_STATUS_MATERIALIZING,
  WYREBOX_ADMIN_HEALTH_STATUS_READ_ONLY,
  WYREBOX_ADMIN_HEALTH_STATUS_STORAGE_FULL,
  WYREBOX_ADMIN_HEALTH_STATUS_STORAGE_ERROR,
  WYREBOX_ADMIN_HEALTH_STATUS_UNAVAILABLE,
} WyreboxAdminHealthStatus;

const char *wyrebox_admin_health_status_state_to_name (
    WyreboxAdminHealthStatus state);

G_END_DECLS
/* *INDENT-ON* */
